
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 1230;
const int acc_off_y = -64;
const int acc_off_z = -1244;
const float acc_scale_x = 15772.250442;
const float acc_scale_y = 16508.460772;
const float acc_scale_z = 17437.174773;

const int magn_off_x = 193;
const int magn_off_y = -54;
const int magn_off_z = -68;
const float magn_scale_x = 470.065815;
const float magn_scale_y = 484.863446;
const float magn_scale_z = 390.132279;
