
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 996;
const int acc_off_y = -56;
const int acc_off_z = -1070;
const float acc_scale_x = 16078.582538;
const float acc_scale_y = 16446.420676;
const float acc_scale_z = 16930.683745;

const int magn_off_x = 204;
const int magn_off_y = -45;
const int magn_off_z = -62;
const float magn_scale_x = 502.886041;
const float magn_scale_y = 467.076855;
const float magn_scale_z = 372.237797;
